name: hairly
description: "나만을 위한 헤어스타일 추천"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  dart_openai: ^5.1.0
  envied: ^1.2.0
  flutter:
    sdk: flutter
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/premium.png
    - assets/hairstyle/color/
    - assets/hairstyle/cut/
    - assets/hairstyle/perm/
  fonts:
    - family: Pacifico
      fonts:
        - asset:  assets/fonts/Pacifico.ttf
    - family: Inklipquid
      fonts:
        - asset: assets/fonts/Inklipquad.otf
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.ttf
        - asset: assets/fonts/NotoSansKR-SemiBold.ttf

